name: Bug report
description: Report a bug in Godot
body:

- type: markdown
  attributes:
    value: |
      - Test

- type: input
  attributes:
    label: Godot version
    description: >
      Test
    placeholder: 3.3.stable, 4.0.dev (3041becc6)
  validations:
    required: true

- type: textarea
  attributes:
    label: Issue description
    description: |
      Test
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      Test
  validations:
    required: true
